name: virulence_annotation_env
dependencies:
  - conda-forge::python=3.7.12
  - conda-forge::python_abi=3.7
  - conda-forge::biopython=1.79
  - conda-forge::numpy=1.21.6
  - conda-forge::pandas=1.3.5
  - conda-forge::scikit-learn=0.21.3
  - conda-forge::pickle5=0.0.12
