name: virulence_annotation_env
dependencies:
  - conda-forge::python=3.7
  - conda-forge::python_abi=3.7
  - conda-forge::biopython=1.77
  - conda-forge::numpy=1.18.5
  - conda-forge::pandas=1.0.5
  - conda-forge::scikit-learn=1.5.1
  - conda-forge::pickle5=0.0.12
