name: virulence_annotation_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - python_abi=3.7
  - snakemake=7.20.0
  - biopython=1.77
  - numpy=1.17.0
  - pandas=1.2.4
  - scikit-learn=0.21.3
  - pickle5=0.0.12
